#! ---------------------------------------------------------------
#! ObsidiaNext Theme for Hexo
#! ---------------------------------------------------------------
#! Designed & Coded By TriDiamond
#! ---------------------------------------------------------------

#! ---------------------------------------------------------------
#! Site Configs
#ï¼ @docs https://obsidianext.tridiamond.tech/guide/configuration.html
#! ---------------------------------------------------------------
site:
  subtitle: Yak's Blog
  author: Yak-0xff
  nick: è¯»ä¹¦å°è®°ã€æŠ€æœ¯æ€è€ƒã€æ ‘æ´...
  description: ä¸€ä½ä¸æ»¡ç°çŠ¶ï¼Œå°±çˆ±çæŠ˜è…¾çš„æŠ€æœ¯äºº <br /> ğŸ¤” <b>å‹¿ä»¥äº‹å°è€Œä¸ä¸º</b>
  language: cn
  multi_language: false
  logo: /img/avatar.jpg
  avatar: /img/avatar.jpg
  beian:
    number: ''
    link: ''

#! ---------------------------------------------------------------
#! Authors Configs
#ï¼ @docs https://obsidianext.tridiamond.tech/guide/authors.html
#! ---------------------------------------------------------------
authors:
  Robin:
    avatar: /img/avatar.jpg
    link: https://github.com/zycslog  
  Yak:
    avatar: /img/avatar.jpg
    link: https://github.com/zycslog  
  # Examples:
  # tom:
  #   name: Tom Cat
  #   avatar: https://img-blog.csdnimg.cn/20210313122054101.png
  #   link: https://github.com/TriDiamond
  # John:
  #   name: John
  #   avatar: https://img-blog.csdnimg.cn/20210313122054101.png
  #   link: https://github.com/TriDiamond

#! ---------------------------------------------------------------
#! Menu Configs
#ï¼ @docs https://obsidianext.tridiamond.tech/guide/menu.html
#! ---------------------------------------------------------------
menu:
  About: true
  Tags: true
  Archives: true
  Starlinks:
    name: "Special Recommended"
    i18n:
      cn: 'ç‰¹åˆ«æ¨è'
      en: 'Special Recommended'
    path: 
    children:
      stevejobsarchive:
        name: 'Steve Jobs Archive'
        path: 'https://stevejobsarchive.com/'
      NetNewsWire:
        name: 'NetNewsWire'
        path: 'https://netnewswire.com/'
  message-board:
    name: 'MessageBoard'
    i18n:
      cn: 'ç•™è¨€æ¿'
      en: 'Message Board'
    path: '/page/message-board'
  # Swift:
  #   name: 'Swift Learning'
  #   i18n:
  #     cn: 'Swiftå­¦ä¹ '
  #     en: 'Swift Learning'
  #   path: '/tags/search?slug=æŠ€æœ¯äººç”Ÿ'

  # projects:
  #   name: 'Projects'
  #   i18n:
  #     cn: 'é¡¹ç›®'
  #     en: 'Projects'
  #   path:
  #   children:
  #     obsidian:
        # name: 'Obsidian Theme'
        # path: 'https://github.com/tridiamond'

#! ---------------------------------------------------------------
#! Theme Config
#! @docs https://obsidianext.tridiamond.tech/guide/theme.html
#! ---------------------------------------------------------------
theme:
  dark_mode: auto
  profile_shape: circle # support `circle`, `diamond`, `rounded`
  feature: true
  gradient:
    color_1: '#24c6dc'
    color_2: '#5433ff'
    color_3: '#ff0099'

#! ---------------------------------------------------------------
#! Social Configs
#! @docs https://obsidianext.tridiamond.tech/guide/social.html
#! ---------------------------------------------------------------
socials:
  github: 'https://github.com/zycslog'
  twitter: 'https://twitter.com/zh_robin'
  stackoverflow: ''
  wechat: ''
  qq: ''
  weibo: ''
  zhihu: ''
  csdn: ''
  juejin: 'https://juejin.cn/user/3104676569682525'

#! ---------------------------------------------------------------
#! Site Meta Configs
#! @docs https://obsidianext.tridiamond.tech/guide/theme.html
#! ---------------------------------------------------------------
site_meta:
  cdn: cn
  favicon:
  description: 'ä¸€ä½ä¸æ»¡ç°çŠ¶ï¼Œå°±çˆ±çæŠ˜è…¾çš„æŠ€æœ¯äººã€‚Robinï¼Œ80åï¼Œä¸»ä¸šiOSå¼€å‘ï¼Œç§»åŠ¨å¼€å‘è€…ï¼Œçƒ­çˆ±æŠ€æœ¯ï¼Œå­¦ä¹ ä¸­ã€‚å¾ˆé«˜å…´èƒ½å¤Ÿåœ¨è¿™é‡Œä¸ä½ åˆ†äº«å¯¹æŠ€æœ¯å¯¹ç”Ÿæ´»çš„æ€è€ƒä¸è®°å½•ã€‚'
  keywords: 'Frontend, Mobile development, Blog, Apple, Swift, SwiftUI, Objective-C'
  author: 'Yak'

#! ---------------------------------------------------------------
#! Plugins
#! ---------------------------------------------------------------

# For local development only!
gitalk:
  enable: false
  autoExpand: true
  clientID: '2324a9799cc77e8a702f'
  clientSecret: '9bca47e66e6b0f41e0217978c57c0bdfb7eb9d2f'
  repo: 'zycslog.github.io'
  owner: 'zycslog'
  admin: ['zycslog']
  id: uid
  language: cn
  distractionFreeMode: false
  recentComment: true
  proxy: ''

# Valine comment plugin (recommended!)
# see https://valine.js.org/quickstart.html
valine:
  enable: true
  app_id: MIq5kQjY23bi6xFLq4FSmnjo-gzGzoHsz
  app_key: ivK9pbbXsipJldb0RfzEL9VU
  avatar: ''
  placeholder: Leave your thoughts behind~
  visitor: true
  lang: cn
  meta: ['nick', 'mail']
  admin: 'Yak'
  recentComment: true

# Enable Busuanzi statistic plugin
# see http://ibruce.info/2015/04/04/busuanzi/
busuanzi:
  enable: true

#! ---------------------------------------------------------------
#! Injections
#! ---------------------------------------------------------------
injects:
  scripts:
  css:


# å¼€å¯ Aurora æœºå™¨äºº Dia
aurora_bot:
  # ======================================================
  # è®¾ç½®ä¸º trueï¼Œä½ å¯çˆ±çš„æœºå™¨äººå°±ä¼šå¯åŠ¨ã€‚
  # ======================================================
  enable: true
  # ======================================================
  # è¯¥æœºå™¨äººæ”¯æŒä¸¤ç§è¯­è¨€
  # -- en: è‹±è¯­
  # -- cn: ä¸­æ–‡
  # ======================================================
  locale: cn
  # ======================================================
  # ç›®å‰åªæ”¯æŒä½¿ç”¨ Diaï¼Œå°†æ¥ä¼šæ”¯æŒ live2dã€‚
  # ======================================================
  bot_type: dia

  # è¿™ä¸ªæŠ€å·§æ˜¯ç”¨æ¥å¯¹ç”¨æˆ·äº¤äº’åšå‡ºååº”çš„
  tips:
    # ======================================================
    # è¿™äº›æ˜¯ Dia æ¯30ç§’ä¼šè¯´çš„éšæœºæ¶ˆæ¯ã€‚
    # ======================================================
    messages:
      - ä½ å¥½ï¼Œæˆ‘æ˜¯ <span>Dia</span>ï¼Œå¥½é«˜å…´é‡è§ä½ ï½
      - å¥½ä¹…ä¸è§ï¼Œæ—¥å­è¿‡å¾—å¥½å¿«å‘¢â€¦â€¦
      - '<span>å¤§åè›‹ï¼</span>ä½ éƒ½å¤šä¹…æ²¡ç†äººå®¶äº†å‘€ï¼Œå˜¤å˜¤å˜¤ï½'
      - å—¨ï½å¿«æ¥é€—æˆ‘ç©å§ï¼
      - æ‹¿å°æ‹³æ‹³é”¤ä½ èƒ¸å£ï¼
      - å­¦ä¹ ä½¿æˆ‘ä»¬å¿«ä¹ï¼Œå¿«ä¹ä½¿æˆ‘ä»¬æ›´æƒ³å­¦ä¹ ï½
      - ä½ çŸ¥é“å—ï¼Ÿä½ å¯ä»¥<span>ç‚¹å‡»æˆ‘</span>è¿”å›é¡µé¢é¡¶éƒ¨å“¦ï¼ï½
      # è¿™æ˜¯ä¸€ä¸ªç‰¹æ®Šçš„å‡½æ•°ï¼Œå®ƒå°†è§¦å‘ quotes API
      # å’Œ Dia ä¼šè¯´å‡ºæ¯æ—¥å¼•ç”¨çš„ä¿¡æ¯ã€‚
      - showQuote

    # ======================================================
    # å°†åœ¨ç”¨æˆ·æ‰“å¼€æµè§ˆå™¨æ§åˆ¶å°æ—¶è§¦å‘ã€‚
    # ======================================================
    console: å“ˆå“ˆï¼Œä½ æ‰“å¼€äº†æ§åˆ¶å°ï¼Œæ˜¯æƒ³è¦çœ‹çœ‹æˆ‘çš„å°ç§˜å¯†å—ï¼Ÿ

    # ======================================================
    # å½“ç”¨æˆ·ä»ä½ çš„åšå®¢ä¸Šå¤åˆ¶å†…å®¹æ—¶è§¦å‘ã€‚
    # ======================================================
    copy: ä½ éƒ½å¤åˆ¶äº†äº›ä»€ä¹ˆå‘€ï¼Œè½¬è½½è¦è®°å¾—åŠ ä¸Šå‡ºå¤„å“¦ï¼

    # ======================================================
    # è¿™å°†åœ¨ç”¨æˆ·è¿”å›çª—å£æ—¶è§¦å‘ã€‚
    # ======================================================
    visibility_change: è€æœ‹å‹ï¼Œä½ æ€ä¹ˆæ‰å›æ¥å‘€ï½

    # ======================================================
    # æ¬¢è¿ç•™è¨€ï¼Œå·ç æ˜¯ä¸€å¤©ä¸­çš„æ—¶é—´ã€‚
    # -----------------------------------
    # eg: 24 = 00:00 ä¹Ÿå°±æ˜¯åˆå¤œ
    # eg: 17-19 = åœ¨ä¸‹åˆ 5 ç‚¹åˆ° 7 ç‚¹ä¹‹é—´
    # -----------------------------------
    # åœ¨ä¸€å¤©çš„è¿™æ®µæ—¶é—´é‡Œï¼ŒDia ä¼šå‘ä½ çš„è¯»è€…é—®å¥½
    # ä¸ç›¸åº”çš„æ¶ˆæ¯ã€‚
    # ======================================================
    welcome:
      '24': ä½ æ˜¯å¤œçŒ«å­å‘€ï¼Ÿè¿™ä¹ˆæ™šè¿˜ä¸ç¡è§‰ï¼Œæ˜å¤©èµ·çš„æ¥å˜›ï¼Ÿ
      '5_7': æ—©ä¸Šå¥½ï¼ä¸€æ—¥ä¹‹è®¡åœ¨äºæ™¨ï¼Œç¾å¥½çš„ä¸€å¤©å°±è¦å¼€å§‹äº†ã€‚
      '7_11': ä¸Šåˆå¥½ï¼å·¥ä½œé¡ºåˆ©å˜›ï¼Œä¸è¦ä¹…åï¼Œå¤šèµ·æ¥èµ°åŠ¨èµ°åŠ¨å“¦ï¼
      '11_13': ä¸­åˆäº†ï¼Œå·¥ä½œäº†ä¸€ä¸ªä¸Šåˆï¼Œç°åœ¨æ˜¯åˆé¤æ—¶é—´ï¼
      '13_17': åˆåå¾ˆå®¹æ˜“çŠ¯å›°å‘¢ï¼Œä»Šå¤©çš„è¿åŠ¨ç›®æ ‡å®Œæˆäº†å—ï¼Ÿ
      '17_19': å‚æ™šäº†ï¼çª—å¤–å¤•é˜³çš„æ™¯è‰²å¾ˆç¾ä¸½å‘¢ï¼Œæœ€ç¾ä¸è¿‡å¤•é˜³çº¢ï½
      '19_21': æ™šä¸Šå¥½ï¼Œä»Šå¤©è¿‡å¾—æ€ä¹ˆæ ·ï¼Ÿ
      '21_23':
        - å·²ç»è¿™ä¹ˆæ™šäº†å‘€ï¼Œæ—©ç‚¹ä¼‘æ¯å§ï¼Œæ™šå®‰ï½
        - æ·±å¤œæ—¶è¦çˆ±æŠ¤çœ¼ç›å‘€ï¼

    # ======================================================
    # å½“ç”¨æˆ·æ¥è‡ªæœç´¢å¼•æ“æ—¶ä½¿ç”¨ã€‚
    # ======================================================
    referrer:
      # ç”¨æˆ·æ¥è‡ªä½ è‡ªå·±çš„ç½‘ç«™ã€‚
      self: æ¬¢è¿æ¥åˆ°<span>ã€Œ[PLACEHOLDER]ã€</span>
      # ç”¨æˆ·æ¥è‡ªç™¾åº¦æœç´¢å¼•æ“ã€‚
      baidu: Helloï¼æ¥è‡ª ç™¾åº¦æœç´¢ çš„æœ‹å‹<br>ä½ æ˜¯æœç´¢ <span>ã€Œ[PLACEHOLDER]ã€</span> æ‰¾åˆ°çš„æˆ‘å—ï¼Ÿ
      # ç”¨æˆ·æ¥è‡ª360æœç´¢å¼•æ“ã€‚
      so: Helloï¼æ¥è‡ª 360æœç´¢ çš„æœ‹å‹<br>ä½ æ˜¯æœç´¢ <span>ã€Œ[PLACEHOLDER]ã€</span> æ‰¾åˆ°çš„æˆ‘å—ï¼Ÿ
      # ç”¨æˆ·æ¥è‡ªè°·æ­Œæœç´¢å¼•æ“ã€‚
      google: Helloï¼æ¥è‡ª è°·æ­Œæœç´¢ çš„æœ‹å‹<br>æ¬¢è¿é˜…è¯»<span>ã€Œ[PLACEHOLDER]ã€</span>
      # ç”¨æˆ·æ¥è‡ªå¦ä¸€ä¸ªç½‘ç«™ã€‚
      site: Helloï¼æ¥è‡ª <span>[PLACEHOLDER]</span> çš„æœ‹å‹
      # ä»»ä½•å…¶ä»–æ¥æºã€‚
      other: æ„Ÿè°¢æ‚¨é˜…è¯»ï¼š <span>ã€Œ[PLACEHOLDER]ã€</span>

    # ======================================================
    # å½“ä½ çš„'é¼ æ ‡æ‚¬åœ'åˆ°ç‰¹å®šçš„HTMLæ ‡ç­¾ï¼ŒDiaå°†
    # ç»™ç”¨æˆ·ç•™è¨€å¸®åŠ©ä»–ä»¬è§£å†³é—®é¢˜ã€‚
    # ------------------------------------------------------
    # selector: æ ‡ç­¾é€‰æ‹©å™¨(ä½ å¯ä»¥ä½¿ç”¨ä»»ä½•cssé€‰æ‹©å™¨)
    # text: è¿™æ˜¯Diaå°†è¦ä¼ è¾¾çš„ä¿¡æ¯ã€‚(å¦‚æœä½ æƒ³è¦çš„
    #       Diaä»ä¸€ç»„ä¿¡æ¯ä¸­éšæœºè¯´å‡ºä¸€ä¸ªï¼Œè®¾ç½®å®ƒ
    #       æ•°ç»„ï¼Œå¦åˆ™åªæ˜¯çº¯æ–‡æœ¬)
    #  ======================================================
    mouseover:
      # æ‚¬æµ®åœ¨ Dia ä¸Š
      - selector: '#Aurora-Dia'
        text:
          - å“‡å•Šå•Šå•Šå•Šå•Šå•Š... <span>ä½ æƒ³å¹²å˜›</span>? O.O
          - è¯·æ‚¨è½»ä¸€ç‚¹ï¼Œæˆ‘æ˜¯<span>å¾ˆæ˜‚è´µ</span>çš„æœºå™¨äººå“¦! O.O
          - '<span>é¢†å¯¼ï¼Œæˆ‘åœ¨å‘¢!</span> æˆ‘æœ‰ä»€ä¹ˆå¯ä»¥å¸®åˆ°ä½ å‘¢? O.O'
      # æ‚¬æµ®åœ¨ Home èœå•
      - selector: "[data-menu='Home']"
        text:
          - ç‚¹å‡»å‰å¾€é¦–é¡µï¼Œæƒ³å›åˆ°ä¸Šä¸€é¡µå¯ä»¥ä½¿ç”¨æµè§ˆå™¨çš„åé€€åŠŸèƒ½å“¦ã€‚
          - ç‚¹å®ƒå°±å¯ä»¥å›åˆ°é¦–é¡µå•¦ï¼
          - å›é¦–é¡µçœ‹çœ‹å§ã€‚
      # æ‚¬æµ®åœ¨ About èœå•
      - selector: "[data-menu='About']"
        text:
          - ä½ æƒ³çŸ¥é“æˆ‘å®¶ä¸»äººæ˜¯è°å—ï¼Ÿ
          - è¿™é‡Œæœ‰ä¸€äº›å…³äºæˆ‘å®¶ä¸»äººçš„ç§˜å¯†å“¦ï¼Œè¦ä¸è¦çœ‹çœ‹å‘¢ï¼Ÿ
          - å‘ç°ä¸»äººå‡ºæ²¡åœ°ç‚¹ï¼
      # æ‚¬æµ®åœ¨ Archives èœå•
      - selector: "[data-menu='Archives']"
        text:
          - è¿™é‡Œå­˜å‚¨äº†ä¸»äººçš„æ‰€æœ‰ä½œå“å“¦ï¼
          - æƒ³çœ‹çœ‹ä¸»äººçš„å›¾ä¹¦é¦†å—ï¼Ÿ
      # æ‚¬æµ®åœ¨ Tags èœå•
      - selector: "[data-menu='Tags']"
        text:
          - ç‚¹å‡»å°±å¯ä»¥çœ‹æ–‡ç« çš„æ ‡ç­¾å•¦ï¼
          - ä½¿ç”¨æ ‡ç­¾å¯ä»¥æ›´å¥½çš„åˆ†ç±»ä½ çš„æ–‡ç« å“¦ï½
      # æ‚¬æµ®åœ¨ language èœå•
      - selector: "[data-dia='language']"
        text: ä¸»äººçš„åšå®¢æ”¯æŒå¤šç§è¯­è¨€ã€‚
      # æ‚¬æµ®åœ¨é»‘ç™½åˆ‡æ¢æŒ‰é’®ä¸Š
      - selector: "[data-dia='light-switch']"
        text: æ‚¨å¯ä»¥ç‚¹å‡»è¿™é‡Œåˆ‡æ¢é»‘ç™½æ¨¡å¼å“¦ï¼
      # æ‚¬æµ®åœ¨ä½œè€…ç®€ä»‹ä¸Š
      - selector: "[data-dia='author']"
        text:
          - è¿™æ˜¯æˆ‘ä¸»äººçš„ç®€ä»‹ã€‚
          - ç‚¹å‡»å…¶ä¸­ä»»ä½•ä¸€ä¸ªé“¾æ¥éƒ½å¯ä»¥ä¼ é€åˆ°æˆ‘ä¸»äººçš„å…¶ä»–ä¸–ç•Œã€‚
      # æ‚¬æµ®åœ¨ä½œè·³è½¬è¯„è®ºæŒ‰é’®ä¸Š
      - selector: "[data-dia='jump-to-comment']"
        text:
          - ä½ æƒ³çœ‹çœ‹è¯„è®ºå—?
          - ç‚¹å‡»è¿™é‡Œå¯ä»¥å¸®åŠ©ä½ ç›´æ¥è·³è½¬åˆ°è¯„è®ºéƒ¨åˆ†ã€‚

    # ======================================================
    # å½“ä½ çš„'é¼ æ ‡ç‚¹å‡»'ä¸ºç‰¹å®šçš„HTMLæ ‡ç­¾ï¼ŒDiaå°†
    # ç»™ç”¨æˆ·ç•™è¨€å¸®åŠ©ä»–ä»¬è§£å†³é—®é¢˜ã€‚
    # ------------------------------------------------------
    # å±æ€§ä¸' moveover 'äº‹ä»¶ç›¸åŒ
    # ======================================================
    click:
      # é¼ æ ‡ç‚¹å‡»æœç´¢æŒ‰é’®
      - selector: "[data-dia='search']"
        text:
          - æ²¡æœ‰çœ‹åˆ°ä½ æƒ³è¦çš„æ–‡ç« ï¼Œé‚£ä¹ˆå°±è¾“å…¥ä½ æƒ³æœç´¢çš„å…³é”®è¯å§ï½
          - å¯ä»¥ä½¿ç”¨ ctrl/cmd + k å¿«æ·é”®æ‰“å¼€æœç´¢å“¦ï½
      # é¼ æ ‡ç‚¹å‡»æ–‡ç« æ ‡é¢˜
      - selector: "[data-dia='article-link']"
        text:
          - å¸Œæœ›ä½ ä¼šå–œæ¬¢è¿™ç¯‡æ–‡ç« ï¼š<span>ã€Œ{text}ã€</span>.
          - æ‚¨çš„é€‰æ‹©çœŸçš„ä¸é”™å“¦ï¼å¥½å¥½äº«å—è¿™ç¯‡æ–‡ç« å§ï½
          - å¸Œæœ›æ‚¨èƒ½ä» <span>ã€Œ{text}ã€</span>è¿™ç¯‡æ–‡ç« ä¸­å­¦åˆ°ç‚¹ä¸œè¥¿ã€‚
      # é¼ æ ‡ç‚¹å‡»è·³è½¬è¯„è®ºè¾“å…¥æ¡†ï¼ˆGitalkï¼‰
      - selector: '.gt-header-textarea'
        text:
          - è¦åæ§½äº›ä»€ä¹ˆå‘¢ï¼Ÿ
          - ä¸€å®šè¦è®¤çœŸå¡«å†™å–µï½
          - æœ‰ä»€ä¹ˆæƒ³è¯´çš„å—ï¼Ÿ
          - å¦‚æœè§‰å¾—æ–‡ç« ä¸é”™çš„è¯ï¼Œå°±ç»™åšä¸»ç•™ä¸ªè¨€å§ï½
      # é¼ æ ‡ç‚¹å‡»è·³è½¬è¯„è®ºè¾“å…¥æ¡†ï¼ˆValineï¼‰
      - selector: '.veditor'
        text:
          - è¦åæ§½äº›ä»€ä¹ˆå‘¢ï¼Ÿ
          - ä¸€å®šè¦è®¤çœŸå¡«å†™å–µï½
          - æœ‰ä»€ä¹ˆæƒ³è¯´çš„å—ï¼Ÿ
          - å¦‚æœè§‰å¾—æ–‡ç« ä¸é”™çš„è¯ï¼Œå°±ç»™åšä¸»ç•™ä¸ªè¨€å§ï½

    # ======================================================
    # åœ¨ç‰¹å®šçš„æ—¥æœŸï¼ŒDiaä¼šå‘ä½ çš„è¯»è€…é—®å€™ã€‚
    # ------------------------------------------------------
    # date: ç‰¹åˆ«æ´»åŠ¨çš„æ—¥æœŸ(æ ¼å¼:æœˆ/æ—¥æˆ–æœˆ/æ—¥-æœˆ/æ—¥)
    # text:
    # ---åªä½¿ç”¨ä¸€ä¸ªç®€å•çš„å­—ç¬¦ä¸²ã€‚
    # -â€”â€”æ¶ˆæ¯çš„éšæœºé›†åˆï¼Œä½¿ç”¨æ•°ç»„é…ç½®æ ¼å¼ã€‚
    # ======================================================
    events:
      - date: 01/01
        text: '<span>å…ƒæ—¦</span>äº†å‘¢ï¼Œæ–°çš„ä¸€å¹´åˆå¼€å§‹äº†ï¼Œä»Šå¹´æ˜¯{year}å¹´ï½'
      - date: 02/14
        text: åˆæ˜¯ä¸€å¹´<span>æƒ…äººèŠ‚</span>ï¼Œ{year}å¹´æ‰¾åˆ°å¯¹è±¡äº†å˜›ï½
      - date: 03/08
        text: ä»Šå¤©æ˜¯<span>å›½é™…å¦‡å¥³èŠ‚</span>ï¼
      - date: 03/12
        text: ä»Šå¤©æ˜¯<span>æ¤æ ‘èŠ‚</span>ï¼Œè¦ä¿æŠ¤ç¯å¢ƒå‘€ï¼
      - date: 04/01
        text: æ‚„æ‚„å‘Šè¯‰ä½ ä¸€ä¸ªç§˜å¯†ï½<span>ä»Šå¤©æ˜¯æ„šäººèŠ‚ï¼Œä¸è¦è¢«éª—äº†å“¦ï½</span>
      - date: 05/01
        text: ä»Šå¤©æ˜¯<span>äº”ä¸€åŠ³åŠ¨èŠ‚</span>ï¼Œè®¡åˆ’å¥½å‡æœŸå»å“ªé‡Œäº†å—ï½
      - date: 06/01
        text: '<span>å„¿ç«¥èŠ‚</span>äº†å‘¢ï¼Œå¿«æ´»çš„æ—¶å…‰æ€»æ˜¯çŸ­æš‚ï¼Œè¦æ˜¯æ°¸è¿œé•¿ä¸å¤§è¯¥å¤šå¥½å•Šâ€¦'
      - date: '09/03'
        text: '<span>ä¸­å›½äººæ°‘æŠ—æ—¥æˆ˜äº‰èƒœåˆ©çºªå¿µæ—¥</span>ï¼Œé“­è®°å†å²ã€ç¼…æ€€å…ˆçƒˆã€ççˆ±å’Œå¹³ã€å¼€åˆ›æœªæ¥ã€‚'
      - date: '09/10'
        text: '<span>æ•™å¸ˆèŠ‚</span>ï¼Œåœ¨å­¦æ ¡è¦ç»™è€å¸ˆé—®å£°å¥½å‘€ï½'
      - date: 10/01
        text: '<span>å›½åº†èŠ‚</span>åˆ°äº†ï¼Œä¸ºç¥–å›½æ¯äº²åº†ç”Ÿï¼'
      - date: 11/05-11/12
        text: ä»Šå¹´çš„<span>åŒåä¸€</span>æ˜¯å’Œè°ä¸€èµ·è¿‡çš„å‘¢ï½
      - date: 12/20-12/31
        text: è¿™å‡ å¤©æ˜¯<span>åœ£è¯èŠ‚</span>ï¼Œä¸»äººè‚¯å®šåˆå»å‰æ‰‹ä¹°ä¹°ä¹°äº†ï½